---
- name: Configurazione Container su macOS
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
  
  tasks:
    - name: Verifica Docker
      command: docker --version
      register: docker_version
      failed_when: false
      changed_when: false
    
    - name: Avviso se Docker non installato
      debug:
        msg: |
          Docker non trovato. Per macOS:
          1. Installa Docker Desktop: https://www.docker.com/products/docker-desktop/
          2. Avvia Docker Desktop
          3. Riavvia il playbook
      when: docker_version.rc != 0
    
    - name: Ferma il playbook se Docker non installato
      fail:
        msg: "Docker non installato. Installare Docker Desktop prima."
      when: docker_version.rc != 0
    
    - include_role:
        name: registry
      vars:
        is_macos: true
    
    - include_role:
        name: container_build
    
    - include_role:
        name: container_deploy